// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLYssVb7rIW2oE1XNL2H2m_2A7lbDxlls',
    appId: '1:101220786771:web:7f14c535a1fdc4308a9ca6',
    messagingSenderId: '101220786771',
    projectId: 'agriculture-15db4',
    authDomain: 'agriculture-15db4.firebaseapp.com',
    storageBucket: 'agriculture-15db4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARQ-ZTiQWW0MuWpup1Huk14WD1AGuT-TE',
    appId: '1:101220786771:android:bdd38f28645654ef8a9ca6',
    messagingSenderId: '101220786771',
    projectId: 'agriculture-15db4',
    storageBucket: 'agriculture-15db4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsxEs-X9ivJ4xRbMvP8sAhGOE6dYgq8iA',
    appId: '1:101220786771:ios:fa5488f01b9ff41d8a9ca6',
    messagingSenderId: '101220786771',
    projectId: 'agriculture-15db4',
    storageBucket: 'agriculture-15db4.appspot.com',
    iosBundleId: 'com.example.mobileapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsxEs-X9ivJ4xRbMvP8sAhGOE6dYgq8iA',
    appId: '1:101220786771:ios:fa5488f01b9ff41d8a9ca6',
    messagingSenderId: '101220786771',
    projectId: 'agriculture-15db4',
    storageBucket: 'agriculture-15db4.appspot.com',
    iosBundleId: 'com.example.mobileapp',
  );
}
